import yellow from "./assets/yellow.png";
import green from "./assets/green.png";
import red from "./assets/red.png";

export const selects = [
  {
    title: "Priority",
    label: "Select",
    disable: "Priority",
    errors: "priority",
    item1: "Low",
    item2: "Normal",
    item3: "High",
    item: ["low", "Normal", "High"],
    image: [yellow, green, red],
  },
  {
    title: "Status",
    label: "Select Status",
    disable: "Select Status",
    errors: "status",
    item: ["Pending", "Active", "Closed"],
    color: ["#FFB72A", "#74D453", "#F25353"],
  },
  {
    title: "Assignee",
    label: "Select",
    errors: "assignee",
    disable: "Assignee",
    item: ["Syed Muqarrab", "Saud Haris", "Saeed"],
  },
];

export const task = [
  {
    id: 1,
    name: "Create Mobile App",
    duedate: "20 jan 2024",
    assignee: "Saud Shaikh",
    priority: "Low",
    image: yellow,
    status: "Pending",
  },
  {
    id: 2,
    name: "Website Design",
    duedate: "25 jan 2024",
    assignee: "Mohammad Zubair",
    priority: "High",
    image: red,
    status: "Active",
  },
  {
    id: 3,
    name: "UI UX Design",
    duedate: "20 jan 2024",
    assignee: "Mohammad Mubashir",
    priority: "Normal",
    image: green,
    status: "Closed",
  },
  {
    id: 4,
    name: "iOS Development",
    duedate: "25 jan 2024",
    assignee: "Sahir Shah",
    priority: "Low",
    image: yellow,
    status: "Pending",
  },
  {
    id: 5,
    name: "Test Api's",
    duedate: "20 jan 2024",
    assignee: "Syed Muqarrab",
    priority: "High",
    image: red,
    status: "Active",
  },
  {
    id: 6,
    name: "Plugin Development",
    duedate: "20 jan 2024",
    assignee: "Mohammad Saeed",
    priority: "Normal",
    image: green,
    status: "Closed",
  },
  {
    id: 7,
    name: "Create Mobile App",
    duedate: "20 jan 2024",
    assignee: "Saud Shaikh",
    priority: "Low",
    image: yellow,
    status: "Pending",
  },
  {
    id: 8,
    name: "Website Design",
    duedate: "25 jan 2024",
    assignee: "Mohammad Zubair",
    priority: "High",
    image: red,
    status: "Active",
  },
  {
    id: 9,
    name: "UI UX Design",
    duedate: "20 jan 2024",
    assignee: "Mohammad Mubashir",
    priority: "Normal",
    image: green,
    status: "Closed",
  },
  {
    id: 10,
    name: "iOS Development",
    duedate: "25 jan 2024",
    assignee: "Sahir Shah",
    priority: "Low",
    image: yellow,
    status: "Pending",
  },
  {
    id: 11,
    name: "Test Api's",
    duedate: "20 jan 2024",
    assignee: "Syed Muqarrab",
    priority: "High",
    image: red,
    status: "Active",
  },
  {
    id: 12,
    name: "Plugin Development",
    duedate: "20 jan 2024",
    assignee: "Mohammad Saeed",
    priority: "Normal",
    image: green,
    status: "Closed",
  },
];
